#!/bin/sh
DIR="$( cd "$( dirname "$0" )" && pwd -P )"

SOX_BIN=$DIR/sox/bin
SOX_INCLUDE=$DIR/sox/include
SOX_LIB=$DIR/sox/lib
SOX_SHARE=$DIR/sox/share

LIBSNDFILE_BIN=$DIR/libsndfile/bin
LIBSNDFILE_INCLUDE=$DIR/libsndfile/include
LIBSNDFILE_LIB=$DIR/libsndfile/lib
LIBSNDFILE_SHARE=$DIR/libsndfile/share

LIBRARY_PATH=""
LIBRARY_PATH=$LIBRARY_PATH"# -- PSYCHO-THERAPY-ASSISTANT ENVIRONMENT VARIABLES START -- #\n"
LIBRARY_PATH=$LIBRARY_PATH"LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:${SOX_BIN}\n"
LIBRARY_PATH=$LIBRARY_PATH"LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:${SOX_INCLUDE}\n"
LIBRARY_PATH=$LIBRARY_PATH"LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:${SOX_LIB}\n"
LIBRARY_PATH=$LIBRARY_PATH"LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:${SOX_SHARE}\n"
LIBRARY_PATH=$LIBRARY_PATH"LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:${LIBSNDFILE_BIN}\n"
LIBRARY_PATH=$LIBRARY_PATH"LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:${LIBSNDFILE_INCLUDE}\n"
LIBRARY_PATH=$LIBRARY_PATH"LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:${LIBSNDFILE_LIB}\n"
LIBRARY_PATH=$LIBRARY_PATH"LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:${LIBSNDFILE_SHARE}\n"
LIBRARY_PATH=$LIBRARY_PATH"export LD_LIBRARY_PATH\n"
LIBRARY_PATH=$LIBRARY_PATH"# -- PSYCHO-THERAPY-ASSISTANT ENVIRONMENT VARIABLES END -- #\n"

echo "Completed setting environment variables\n";
#echo $LIBRARY_PATH >> ~/.bashrc
#echo $LIBRARY_PATH >> ~/.profile


. ~/.bashrc
. ~/.profile

#echo 'export APP=/opt/tinyos-2.x/apps' >> ~/.bashrc 

#echo  'export TOS=/opt/tinyos-2.x/tos' >> ~/.bashrc 

#LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/scratch/kedu14/woojung/sox/include
